### ISSUE TITLE
arrow falls off of side, when page margin is close

### ISSUE THREAD

**Issue by jasonday** [goldfire/miniTip#13] opened 2012-07-11 20:35 UTC
![Imgur](http://i.imgur.com/Oxy7Y.jpg)

edge of viewport is close to the left - arrow falls off side .

maybe a minimum offset would fix? or if the plugin would switch to east/west at that point?

**Comment by goldfire** [comment] 2012-07-11 22:13
Can you setup an example on http://jsfiddle.net/ or provide the link to the page with that issue so I can look at your implementation? So far I've been unable to replicate this issue.

**Comment by jasonday** [comment] 2012-07-11 23:52
Hey - thanks for responding so quickly. Here's a fiddle - http://jsfiddle.net/jasonday/Y6ERV/
The issue is caused by my styling having a larger border radius - 10px.
May be worth not putting the tip at the far edge (offset 10px or so) to help alleviate styling conflicts. 

Additionally, it may be worth looking at fully dynamic positioning - so y axis triggers n/s (current state) and x axis triggers e/w.

Also, I've tested my pull request, with the addition of the option className - and it works great. I set className in my miniTips call, and the output is #miniTip.myClass - which I use for multiple styles. Great plugin! perfect for my needs, as I was using qtip, which was way too bloated. I have a couple of ideas about how to implement ajax with minimal code, but I'll need to look at it further. I'll let you know.

**Comment by goldfire** [comment] 2012-07-12 02:38
Ah I see, thanks for setting up the fiddle. I'll get that fixed and merge the pull request soon. This is a pretty crazy week, otherwise I'd have already done it.

**Comment by jasonday** [comment] 2012-07-13 18:00
I hacked a fix - but it's not a long term solution:
`mLeft = mLeft < 0 ? aLeft + mLeft -10 : aLeft;
aLeft = 10;`

**Comment by goldfire** [comment] 2012-07-13 18:38
This is now fixed in v1.5.2. Thanks!

**Closed as completed by goldfire** 2012-07-13 18:38 UTC

**Comment by goldfire** [comment] 2012-07-13 18:43
Oh sorry, didn't notice you had posted (was working on the fix while you posted). I think we did something similar, but the fix I added repositions the arrow based on the size of the border-radius. From my testing it should work as expected now.

**Comment by jasonday** [comment] 2012-07-13 18:49
I'm seeing a new bug now. After first hover - second hover is off the mark.

![Imgur](http://i.imgur.com/YLMnc.jpg)

**Comment by goldfire** [comment] 2012-07-13 19:47
I'm unable to reproduce this on http://jsfiddle.net/Y6ERV/2/ (updated with 1.5.2), any idea what is different there from the fiddle?

**Comment by jasonday** [comment] 2012-07-13 20:11
Look at it in Firefox - I'm running 13 - chrome works fine. But in Firefox, the calculation isn't happening/rendering correctly - so I think it's then producing another error (such as the offset tooltip in my screenshot above).

IE break entirely. So something's off in that new calculation.

**Comment by jasonday** [comment] 2012-07-13 20:16
I just realized the issue - your calculation is looking for "border-radius" specifically, but not looking for other variations: 

`-webkit-border-radius: 10px;`
`-moz-border-radius: 10px;`
`border-radius: 10px;`

wondering if jQuery's .cssHooks might work (might be overkill too)
http://api.jquery.com/jQuery.cssHooks/

**Comment by jasonday** [comment] 2012-07-13 20:22
A simpler approach, might be to include a x-offset option - so a user can input the border radius, or desired offset, for when the arrow goes to the corner. (a much smaller amount of code).

**Comment by jasonday** [comment] 2012-07-13 20:39
see new pull request patch and fiddle:
http://jsfiddle.net/jasonday/Y6ERV/3/

works like a charm

**Comment by jasonday** [comment] 2012-07-13 20:51
update: see className and tipOff working here:

http://jsfiddle.net/jasonday/Y6ERV/ 

the only issue is that with className, it does not seem to work with multiple styles on the same page.

**Comment by goldfire** [comment] 2012-07-16 04:27
Your suggested fix for the offset will be getting pushed shortly, I'm not going to have a chance to look at the className idea tonight however.

**Comment by jasonday** [comment] 2012-07-16 12:35
~~Something you changed in the new version, has made it so that className isn't working properly. I'll need to look at what's changed.It appears that className isn't being picked up from the config object in the call~~

my own mistake - I was using a tainted file (one of my experiment files)...
